name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
    types: [opened, synchronize]
  pull_request_review:
    branches: [master]
    types: [submitted]

jobs:
  all-jobs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: haskell/actions/setup@v1
        with:
          enable-stack: true
          stack-version: 'latest'
      - name: Cache Haskell build
        uses: actions/cache@v2
        with:
          path: ~/.stack
          key: stack-cache-${{ hashFiles('stack.yaml') }}-${{ hashFiles('techblog.cabal') }}
          restore-keys: |
            stack-cache-${{ hashFiles('stack.yaml') }}
      - name: Build
        run: stack build
      - name: Build the site
        run: stack exec -- techblog generate
      # TODO(mihaimaruseac): Validation is flaky, so we disable it for now
      # name: Validating URLs in the site
      # run: stack exec -- techblog validate
      # TODO(mihaimaruseac): Cannot immediately deploy as pushes to the branch are disabled
      # (https://github.community/t/allowing-github-actions-bot-to-push-to-protected-branch/16536/2)
      #- name: Deploying the site
      #  if: ${{ github.event_name == 'push' }}
      #  run: |
      #    git config --global user.email "techblog@rosedu.org"
      #    git config --global user.name "ROSEdu Techblog"
      #    stack exec -- techblog deploy
