name: CI

on:
  push:
    branches: [master]

jobs:
  checkout:
    name: Checkout repository
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
  build-generator:
    name: Generating the binary
    needs: checkout
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-haskell@v1
        with:
          enable-stack: true
          stack-version: 'latest'
      - name: Cache Haskell build
        uses: actions/cache@v2
        with:
          path: ~/.stack
          key: stack-cache-${{ hashFiles('stack.yaml') }}-${{ hashFiles('techblog.cabal') }}
          restore-keys: |
            stack-cache-${{ hashFiles('stack.yaml') }}
      - name: Build
        run: stack build
  build-site:
    name: Generating the website
    needs: build-generator
    runs-on: ubuntu-latest
    steps:
      - name: Build the site
        run: stack exec -- techblog generate
      - name: Debug
        run: echo "OK, works"
