name: CI

on:
  push:
    branches: [master]

jobs:
  build:
    name: Generating the website
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Debug
        run: echo "OK, works"
