name: CI

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-haskell@v1
        with:
          enable-stack: true
          stack-version: 'latest'
      - name: Cache Haskell build
        uses: actions/cache@v2
        with:
          path: ~/.stack
          key: stack-cache-${{ hashFiles('stack.yaml') }}-${{ hashFiles('techblog.cabal') }}
          restore-keys: |
            stack-cache-${{ hashFiles('stack.yaml') }}
      - name: Build
        run: stack build
      - name: Build the site
        run: stack exec -- techblog generate
      - name: Validating URLs in the site
        run: stack exec -- techblog validate
      - name: Deploying the site
        run: echo stack exec -- techblog deploy
